### ISSUE TITLE
feedly のアイコンをマウスホバーしてもハイライトされない

### ISSUE THREAD

**Issue by syoichi** [jser/jser.github.io#33]
JSer.info のサイトのサイドバーにある Twitter、GitHub、RSS Feed のアイコンはマウスをあてると色が薄くなるのですが、feedly のアイコンは変化しないようになっています。

![screenshot1](https://cloud.githubusercontent.com/assets/69238/5639541/cb6651d6-965b-11e4-8ef8-4663dcf12f11.jpg)
![screenshot2](https://cloud.githubusercontent.com/assets/69238/5639546/d3bc1d98-965b-11e4-9ea0-e240f5ca2bdf.jpg)

**Comment by azu** [comment]
@syoichi Thanks! Fixed it!

![fixed](http://gyazo.com/3845808676b36693553814ecff6c5a66.gif)

**Comment by syoichi** [comment]
修正を確認しました。ありがとうございました。
