### ISSUE TITLE
文の間の改行が半角スペースになっている

### ISSUE THREAD

**Issue by syoichi** [jser/jser.github.io#35]
これは以前からある問題でしたが、[Markdown の仕様](https://ja.wikipedia.org/wiki/Markdown#.E6.94.B9.E8.A1.8C)により、Markdown で書かれた記事における文の間の 1 つの改行が、最終的な記事上では改行として反映されず半角スペースになってしまっています。

2 つの改行を入れるとパラグラフとして文同士が離れてしまう為、Markdown で書く場合は改行とともに文末に 2 つの半角スペースを入れると良いのですが、GitHub と同じように、Markdown を HTML に変換する時に何らかの方法で現状でもうまく改行が反映できると良さそうですね。
あるいは、改行としても半角スペースとしても反映せずに、何も挿入されないようにするのも良いかもしれません。

**Comment by azu** [comment]
現状

[![](http://monosnap.com/image/XaYn3I4ag5zzcWNR86Tf5em65TYU1I.png)](http://jser.info/2015/01/13/6to5-jspm-refactoring-javascript/ "2015-01-13のJS: 6to5、ES6とjspm、リファクタリングJavaScript - JSer.info")

reacapredで[:hard_wrap](https://github.com/vmg/redcarpet#darling-i-packed-you-a-couple-renderers-for-lunch "vmg/redcarpet")オプションを有効にしたケース

[![hard_wrap](http://monosnap.com/image/kTsqd1wDJSIPa23zty3Alrsptj7dpu.png)](https://cloud.githubusercontent.com/assets/19714/5734906/81f6d584-9c00-11e4-97b1-4b27733cc069.png)

**Comment by syoichi** [comment]
スクリーンショットを見た限りではうまく改行が反映されているようですが、:hard_wrap オプションを有効にした場合に何か問題があるのでしょうか?

**Comment by azu** [comment]
あー、まだオプションを有効にしてなかっただけです。 :soon:

**Comment by azu** [comment]
`:hard_wrap` 有効化しました

**Comment by syoichi** [comment]
改行の反映を確認しました! ありがとうございました!
