### ISSUE TITLE
CONTRIBUTING内のPull Requestのリンクが切れている

### ISSUE THREAD

**Issue by tkhm** [jser/jser.github.io#412]
CONTRIBUTIONG.md内にあるPRのリンクが切れているようです。
master, develop, jser-week-337いずれのブランチの[CONTRIBUTING.md](https://github.com/jser/jser.github.io/blob/develop/CONTRIBUTING.md)でも確認できました。

Chromeで確認すると次のように表示されます。

![2017-06-21 at 10 18 57](https://user-images.githubusercontent.com/6651854/27362688-14311d3e-566b-11e7-91be-72800f141445.jpg)

[遷移先](https://camo.githubusercontent.com/a0887342a26d460a74ede4bb8ef2f1ec8327e6d9/687474703a2f2f74616b652e6d732f7375773549)では次のようなエラーが表示されます。

`Error Fetching Resource`

**Comment by azu** [comment]
ありがとうございます。
画像がリンク切れ起こしてるみたいですね。
(リンク先も画像)

たしかこの部分のスクショだった気がします。
![image](https://user-images.githubusercontent.com/19714/27381399-ad87b586-56bd-11e7-954e-3f8ea33fff99.png)

あとで修正しておきます
