### ISSUE TITLE
Markdownで書かれたリンクの生成方法について、いくつか改善した方が良い問題がある

### ISSUE THREAD

**Issue by syoichi** [jser/jser.github.io#58]
特に「harmony:specification_drafts」のリンク([参考](https://github.com/jser/jser.github.io/commit/145ad29bd8b74a87f229aa2f9355b0fc55451f84#diff-bd963cef7f5e28d689933f769dfbc695L112))で目立っているのですが、テキストとしてのURLに含まれるアンダースコア(_)がバックスラッシュ(\\)でエスケープされていない為、該当の部分がイタリック体で表示されてしまっているという問題があります。

逆に、リンクのタイトルではバックスラッシュによるエスケープは必要ないようで、リンクのタイトルに関するツールチップの表示時にバックスラッシュが表示されてしまうという問題もあります。こちらの問題ではアンダースコアだけでなくブラケット([])も対象となっているようです。

リンクとしてのURLに関してはエスケープは必要ないはずですから、この辺りの問題をうまく解決するように、Markdownで書かれたリンクの生成方法を改善できると良いですね。

**Comment by azu** [comment]
Markdownのエンジンに左右されやすいので、エスケープの方針だと難しいなー。
Aタグを使うのが確実でいいけど、Markdownであることを捨ててしまうのはどうなんだろというところはある。。でもtagsはむりなので捨ててるしなー

InlineCodeの無害版があればそれを使うのが良さそうだけど、ないのでイマイチ感がある…

[`wiki.ecmascript.org/doku.php?id=harmony:specification_drafts#april_3_2015_rev_37_release_candidate_4`](http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts#april_3_2015_rev_37_release_candidate_4 "harmony:specification\_drafts \[ES Wiki\]")

-----

- Aタグを使う
- エスケープ頑張る
- InlineCode + Styleパッチ

あたりかなー

**Comment by azu** [comment]
[mdast](http://mdast.js.org/ "mdast - markdown processor powered by plug-ins")でチェックできるようにするのがよさそう。

- `[&#x27;]()`
- `[_]()`

**Comment by azu** [comment]
https://github.com/jser/jser.info/commit/0e29f7d5eed0ec5cd0c26223222f993dc3248884 
それっぽく直したつもり

**Comment by azu** [comment]
Pattern

```
## Surfin' Safari - Blog Archive » ES6 in WebKit

[yoshiko-pg.github.io/slides/20151015-gp-meetup/](http://yoshiko-pg.github.io/slides/20151015-gp-meetup/ "AngularJSの$watch登録数が60,000だった - @yoshiko_pg")
```

**Comment by syoichi** [comment]
最近の記事ではだいぶこの問題が見られなくなってきましたね。色々と対処して頂きありがとうございます。
まだ細かい問題は残っているかもしれませんが、目立った問題は解決されたようですので、とりあえずこのIssueはCloseにします。
