### ISSUE TITLE
add lang([lang="ja"]) attribute in html tag.

### ISSUE THREAD

**Issue by skt-t1-byungi** [jser/jser.github.io#795]
https://github.com/jser/jser.github.io/blob/7009ffdc3c90168799ded81ac16ff7cf71d4df19/_layouts/default.html#L2

I use Google Translator because I don't know Japanese, 
but the translator translates the page into English. I think lang attribute will help translator recognize it as a Japanese page.

(I am not Japanese but I like jser)

**Comment by azu** [comment]
@skt-t1-byungi Thanks!

I've added `lang="ja"` in #796 
It will be released as soon https://travis-ci.org/github/jser/jser.github.io/builds/738202502
