### ISSUE TITLE
Support Multiple Languages

### ISSUE THREAD

**Issue by azu** [jser/jser.github.io#83]
[JSer.info](http://jser.info/) support i18n.

e,g.) http://jser.info/kr/

- [x] Introduce [Multiple Languages in Jekyll](https://github.com/screeninteraction/jekyll-multiple-languages-plugin "Multiple Languages in Jekyll")
- [x] Check i18n template
      - Link, RSS, SNS button?
- [x] Add Collaborators ( https://github.com/orgs/jser/teams/contributors )
- [x] Setup CI for auto deploy(Default branch is master, Travis CI deploy to gh-pages)
      - Curently, rely on Github's [Jekyll](https://help.github.com/articles/using-jekyll-with-pages/ "Jekyll").
      - if use external jekyll plugin like [Multiple Languages in Jekyll](https://github.com/screeninteraction/jekyll-multiple-languages-plugin "Multiple Languages in Jekyll"), have to build by hand or CI.
      - [Continuous Integration](http://jekyllrb.com/docs/continuous-integration/ "Continuous Integration")
      - [jirutka/rake-jekyll](https://github.com/jirutka/rake-jekyll "jirutka/rake-jekyll")

**Comment by azu** [comment]
- [ ] wait fixed [GH_TOKEN is leaked · Issue #8 · jirutka/rake-jekyll](https://github.com/jirutka/rake-jekyll/issues/8 "GH_TOKEN is leaked · Issue #8 · jirutka/rake-jekyll")

**Comment by azu** [comment]
- [ ] re-re-reverrt #86

**Comment by azu** [comment]
やっと、i18n版をデプロイできました :tada: 

まとめると

- [User &amp; Organization Pages](https://help.github.com/articles/user-organization-and-project-pages/ "User &amp; Organization Pages")の場合は`master`ブランチに置いたHTMLがそのまま表示される
- 逆にプロジェクトページだと`gh-pages`ブランチに置いたHTMLがそのまま表示される
- jser//jser.github.ioは Organization Pagesなので master ブランチに対して生成物をデプロイする！
- `develop`ブランチが開発ブランチ = markdown等のソースが置いてあるブランチ

**Comment by azu** [comment]
- [ ] rename master to develop (link...)

**Comment by UYEONG** [comment]
:+1:

**Comment by azu** [comment]
@UYEONG さんを[jser](https://github.com/jser) organizationのCollaboratorsにInviteしました。

#116 で色々チェックスクリプトも実装したので、このIssue関連はこれで完了したのでCloseします。
